# -*- coding: utf-8 -*-
"""dever_de_casa03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZZB4hVymjiOBejOLrWACxxvp0RISt6E
"""

import csv

# Cria o arquivo CSV
with open('dados.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Nome', 'Idade'])
    writer.writerow(['Ana', 25])
    writer.writerow(['Bruno', 30])
    writer.writerow(['Carla', 22])
    writer.writerow(['Daniel', 28])
    writer.writerow(['Eduardo', 35])

# Lê o arquivo CSV e armazena os dados em uma lista
dados = []
with open('dados.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        dados.append(row)

# Solicita ao usuário para digitar um nome
nome_digitado = input("Digite um nome: ").capitalize()

# Verifica se o nome digitado está na lista (ignorando maiúsculas/minúsculas)
nome_encontrado = False
for pessoa in dados:
    if pessoa['Nome'].capitalize() == nome_digitado:
        nome_encontrado = True
        idade = int(pessoa['Idade'])

        # Encontra a pessoa mais velha
        idades = [int(pessoa['Idade']) for pessoa in dados]
        pessoa_mais_velha = max(idades)

        # Exibe o nome, idade e se é a pessoa mais velha
        if idade == pessoa_mais_velha:
            print(f"{pessoa['Nome']} tem {idade} anos, é a pessoa mais velha da lista.")
        else:
            print(f"{pessoa['Nome']} tem {idade} anos, não é a pessoa mais velha da lista.")
        break

# Se o nome não for encontrado
if not nome_encontrado:
    print(f"Nome '{nome_digitado}' não encontrado na lista.")

import csv

# Cria o arquivo CSV
with open('dados.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Nome', 'Idade'])
    writer.writerow(['Ana', 25])
    writer.writerow(['Bruno', 30])
    writer.writerow(['Carla', 22])
    writer.writerow(['Daniel', 28])
    writer.writerow(['Eduardo', 35])

# Lê o arquivo CSV e armazena os dados em uma lista
dados = []
with open('dados.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        dados.append(row)

# Solicita ao usuário para digitar um nome
nome_digitado = input("Digite um nome: ").capitalize()

# Verifica se o nome digitado está na lista (ignorando maiúsculas/minúsculas)
nome_encontrado = False
for pessoa in dados:
    if pessoa['Nome'].capitalize() == nome_digitado:
        nome_encontrado = True
        idade = int(pessoa['Idade'])

        # Encontra a pessoa mais velha
        idades = [int(pessoa['Idade']) for pessoa in dados]
        pessoa_mais_velha = max(idades)

        # Exibe o nome, idade e se é a pessoa mais velha
        if idade == pessoa_mais_velha:
            print(f"{pessoa['Nome']} tem {idade} anos, é a pessoa mais velha da lista.")
        else:
            print(f"{pessoa['Nome']} tem {idade} anos, não é a pessoa mais velha da lista.")
        break

# Se o nome não for encontrado
if not nome_encontrado:
    print(f"Nome '{nome_digitado}' não encontrado na lista.")