# -*- coding: utf-8 -*-
"""dever_de_casa02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ae8aG2UY8BcAoRU7pjpr_7lLaacTT2e_
"""

#Entrada do usuário

def obter_frase():
    while True:
        frase = input("Digite uma frase: ").strip()
        if frase:
            return frase
        print("Erro: A entrada não pode estar vazia. Tente novamente.")


# Analisar a frase
def analisar_frase(frase):
    num_caracteres = len(frase)
    palavras = frase.split()
    num_palavras = len(palavras)
    maior_palavra = max(palavras, key=len) if palavras else ""

    return num_caracteres, num_palavras, maior_palavra, palavras

#Manipulação das palavras e frases
def manipular_frase(frase, palavras):
    frase_invertida = frase[::-1]
    palavras_invertidas = " ".join(reversed(palavras))
    frase_maiuscula = frase.upper()
    frase_minuscula = frase.lower()
    tupla_palavras = tuple(palavras)

    return frase_invertida, palavras_invertidas, frase_maiuscula, frase_minuscula, tupla_palavras

# Programa principal
frase_usuario = obter_frase()
num_caracteres, num_palavras, maior_palavra, palavras = analisar_frase(frase_usuario)
frase_invertida, palavras_invertidas, frase_maiuscula, frase_minuscula, tupla_palavras = manipular_frase(frase_usuario, palavras)

# Analise da frase
print("\n===== Análise da Frase =====")
print(f"Número total de caracteres: {num_caracteres}")
print(f"Número total de palavras: {num_palavras}")
print(f"Maior palavra: {maior_palavra}")
print("\n===== Manipulação e Formatação =====")
print(f"Frase invertida (por caracteres): {frase_invertida}")
print(f"Frase com palavras invertidas: {palavras_invertidas}")
print(f"Frase em maiúsculas: {frase_maiuscula}")
print(f"Frase em minúsculas: {frase_minuscula}")
print(f"Tupla de palavras: {tupla_palavras}")

